version: '3'

services:
  rabbitmq:
    container_name: monster-rabbitmq
    image: rabbitmq:3.7.8-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    container_name: monster-redis
    image: redis
    ports:
    - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
    - redis-data:/data

volumes:
  rabbitmq-data:
  redis-data:
